services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: userflow
      POSTGRES_HOST: localhost
    ports:
      - 5432:5432
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
